name: expenses_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.69.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.0.3
  uuid: ^4.3.3

  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  flutter_slidable: ^3.1.1
  firebase_auth: ^4.16.0
  table_calendar: ^3.0.0
  firebase_messaging: ^14.9.4
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^7.0.1


  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  expense_repository:
    path: packages/expense_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    -  lib/images/


