// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWsqDoCDG9xjsKfBNI6j9V3exLUq8f32s',
    appId: '1:13701743979:web:24ef32307f6b1f0cb0b82e',
    messagingSenderId: '13701743979',
    projectId: 'flutter-expense-tracker-a6400',
    authDomain: 'flutter-expense-tracker-a6400.firebaseapp.com',
    storageBucket: 'flutter-expense-tracker-a6400.firebasestorage.app',
    measurementId: 'G-N78TXZKH8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_9SV39BIwuOQULX_mUp0w3c2KdEU5oJ8',
    appId: '1:13701743979:android:60fa475309e13ec4b0b82e',
    messagingSenderId: '13701743979',
    projectId: 'flutter-expense-tracker-a6400',
    storageBucket: 'flutter-expense-tracker-a6400.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACnUqXSz5J02XrP2fedQDJczRkwgxwBzk',
    appId: '1:13701743979:ios:26da443511ba4906b0b82e',
    messagingSenderId: '13701743979',
    projectId: 'flutter-expense-tracker-a6400',
    storageBucket: 'flutter-expense-tracker-a6400.firebasestorage.app',
    iosBundleId: 'com.example.cw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACnUqXSz5J02XrP2fedQDJczRkwgxwBzk',
    appId: '1:13701743979:ios:26da443511ba4906b0b82e',
    messagingSenderId: '13701743979',
    projectId: 'flutter-expense-tracker-a6400',
    storageBucket: 'flutter-expense-tracker-a6400.firebasestorage.app',
    iosBundleId: 'com.example.cw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ar-jqsGX3sH0XygbOAijCLqmLtVCnR4',
    appId: '1:13701743979:web:b8953aeeb48fad6db0b82e',
    messagingSenderId: '13701743979',
    projectId: 'flutter-expense-tracker-a6400',
    authDomain: 'flutter-expense-tracker-a6400.firebaseapp.com',
    storageBucket: 'flutter-expense-tracker-a6400.firebasestorage.app',
    measurementId: 'G-GGGKE0MPL1',
  );
}
